#ifndef __BF_STATUS_MINI_SYSTEM_H__
#define __BF_STATUS_MINI_SYSTEM_H__
#include "stm32f10x.h"
#include "mpu6050.h"
#include "led.h"
#include "hmc5883l.h"
#include "imu.h"
#include "debug_usart.h"
#include "motor.h"
#include <stdio.h>
#include "stm32fx_delay.h"
#include "nrf24l01.h"
void time_init(void);
void system_init(void);
void Time_slice(void);
void Flag_Clear(void);
void param_init(void);
void data_load(void);
void data_save(void);
#endif
